### ISSUE TITLE
Command line skip flag doesn't work

### ISSUE THREAD

**Issue by roryjtowler** [Ozsie/detekt-maven-plugin#106]
Hi I'm doing the command maven clean install and I've gotten Detekt working for the most part. Its finds the issues with the code, that's all fine. But I'd like to be able to run a clean install without Detekt. Here is what I have so far:

 ```
 <plugin>
          <groupId>com.github.ozsie</groupId>
          <artifactId>detekt-maven-plugin</artifactId>
          <version>1.17.1</version>
          <executions>
              <execution>
                  <phase>verify</phase>
                  <goals><goal>check</goal></goals>
                  <configuration>
                      <config>detekt.yml</config>
                  </configuration>
              </execution>
          </executions>
</plugin>
```

`mvn -T 2C clean install -Ddetekt.skip=true -U`

When I add skip to pom file it skips it, but doesn't seem to be working as a command line parameter.

Any help would be great.

Expected result:
maven is ran without detekt

Actual result:
maven is ran with detekt

**Comment by roryjtowler** [comment]
I understand that I could remove the execution from the pom file and specifically run the 'mvn detekt:check' but it would be nice to be able to include it or exclude it from the clean install based on some param

**Comment by Ozsie** [comment]
I'll have a look at this

**Comment by roryjtowler** [comment]
Thanks!

**Comment by roryjtowler** [comment]
This works now, thanks
