### ISSUE TITLE
Plugin can't be run from a parent multi-module project

### ISSUE THREAD

**Issue by reubenfirmin** [Ozsie/detekt-maven-plugin#13]
The plugin works when run on each module, but you can't run it on the parent module directly. 

It fails with:

[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0.RC9.2:check (default-cli) on project parent: Execution default-cli of goal com.github.ozsie:detekt-maven-plugin:1.0.0.RC9.2:check failed: Provided path '/x/y/z/javaapis/src' does not exist! -> [Help 1]
[ERROR]

**Comment by Ozsie** [comment]
I will look into it.

**Comment by robinkanters** [comment]
I'm running into this as well. Would be enough if I could specify the input paths but the config documentation seems scarce to me on this subject

**Comment by reubenfirmin** [comment]
I found a solution of sorts; adding a profile which ignores the plugin when on the parent module.

```
    <profiles>
        <profile>
            <id>kotlin</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.ozsie</groupId>
                        <artifactId>detekt-maven-plugin</artifactId>
                        <version>1.0.0.RC9.2</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <activation>
                <file>
                    <exists>${basedir}/src/main/kotlin</exists>
                </file>
            </activation>
        </profile>
    </profiles>
```

**Comment by blakemorgan** [comment]
I am having this same problem as well.

**Comment by Ozsie** [comment]
This is an issue with how detekt works by default, though it makes no real sense to fail because of this in this case. I will try to implement some work around

**Comment by Ozsie** [comment]
This should be working in detekt-maven-plugin 1.0.0-RC14
