### ISSUE TITLE
Please add an option to avoid failOnError

### ISSUE THREAD

**Issue by reubenfirmin** [Ozsie/detekt-maven-plugin#14]
Use case: this is running as part of a jenkins build. We want the reporting, but we don't want it to fail the build on error.

As it stands, it will fail with an error like:
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0.RC9.2:check (default) on project base: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0.RC9.2:check failed: Build failed with 123 weighted issues (threshold defined was 10). -> [Help 1]

**Comment by Ozsie** [comment]
This feels more like a detekt configuration issue, the default configuration of detekt is to fail if 10 or more issues are found, since this plugin only wraps detekt it cannot determine if the scan was successful or not.
