### ISSUE TITLE
Updating from 1.21.0 to 1.21.0.1 causes finding a lot of new issues

### ISSUE THREAD

**Issue by var314** [Ozsie/detekt-maven-plugin#156]
Hi,

It seems that the main change in 1.21.0.1 is providing a classpath to Detekt, which enables Type Resolution and a lot of new rules. I fixed most of the issues but some of them are hard to solve and misbehave. E.g. it properly detected `UnsafeCallOnNullableType` cases. `mvn detect:check` reports the issues but `mvn detekt:cb` does not add anything to baseline.xml.

Other issue I run into is that the detekt plugin was used in validation phase in my project, to quickly check the code. Now it has to be used after compilation, because it requires compiled classes.

Last but not least, the Type Resolution is said to be experimental in [Detekt documentation](https://detekt.dev/docs/gettingstarted/type-resolution).

So maybe it should be not enabled by default? Also, I have found no way of disabling it. Maybe something similar to [gradle plugin](https://detekt.dev/docs/gettingstarted/type-resolution#enabling-on-a-jvm-project) would be good? It has different tasks to run Detekt with or without Type Resolution.

**Comment by stephan-strate** [comment]
We are seeing similar problems when updating from 1.21.0 to 1.21.0.1.
As far as I see no additional rules should be activated in this release, right?

**Comment by erwinc1** [comment]
Same here, and an additional error [as described here](https://github.com/Ozsie/detekt-maven-plugin/issues/160)

**Comment by Ozsie** [comment]
Hi, sorry for the very late reply.

I will move the check with default class path to it's own task. I don't want to release it until detekt 1.22.0 is out though.

In the mean time, downgrading to 1.21.0 should work as this was the only change in 1.21.0.1.

You can check out the PR here if you like: #164

I hope this will solve the issue and that downgrading in the meantime is enough.

**Comment by Ozsie** [comment]
Version [1.22.0](https://github.com/Ozsie/detekt-maven-plugin/releases/tag/1.22.0) is released, I hope that this version will solve your issues.

It includes the changes in PR #164, and bumps the version of detekt up to 1.22.0
