### ISSUE TITLE
Can't add UnnecessaryAbstractClass issue to ignore

### ISSUE THREAD

**Issue by mikamikaWolt** [Ozsie/detekt-maven-plugin#158]
I have an issue reported for my project (maven, Kotlin, plugin version 1.21.0.1):
`BaseScreen.kt:10:16: An abstract class without an abstract member can be refactored to a concrete class. [UnnecessaryAbstractClass]`

Running `mvn detekt:cb` doesn't add it to a baseline.

**Comment by Ozsie** [comment]
I would probably take this issue to the detekt project instead. This plugin only wraps the detekt cli which is responsible for actually generating the baseline file
