### ISSUE TITLE
Support for report / output CLI parameters

### ISSUE THREAD

**Issue by reubenfirmin** [Ozsie/detekt-maven-plugin#16]
Detekt had "output" and has moved to "report". Please support it.

**Comment by Ozsie** [comment]
This is coming, I am working on moving this plugin to the latest detekt release

**Comment by Ozsie** [comment]
All current detekt cli parameters should now be supported in detekt-maven-plugin 1.0.0-RC14

**Comment by reubenfirmin** [comment]
I tested with 1.0.0-RC14 and "report" isn't working. I don't see it in here either: https://github.com/Ozsie/detekt-maven-plugin/blob/master/src/main/java/com/github/ozsie/DetektMojo.kt

**Comment by Ozsie** [comment]
Reopening as it is still not working
