### ISSUE TITLE
Support for report / output CLI parameters

### ISSUE THREAD

**Issue by reubenfirmin** [Ozsie/detekt-maven-plugin#18]
I don't see a way to reopen issues, sorry for the duplicate.

Doesn't appear that https://github.com/Ozsie/detekt-maven-plugin/issues/16 is fixed.

**Comment by Ozsie** [comment]
1.0.0-RC14-1 released with support for one report format at a time. I am working on support for multiple formats.

**Comment by Ozsie** [comment]
Added support for multiple report formats in 1.0.0-RC14-2
