### ISSUE TITLE
Support for build-upon-default-config and fail-fast CLI parameters

### ISSUE THREAD

**Issue by masondoom** [Ozsie/detekt-maven-plugin#22]
Hi,

I am trying to use this plugin and add some overrides on detekt config. However, `build-upon-default-config` and `fail-fast` options are not supported. (Seeing those options from [here](https://arturbosch.github.io/detekt/cli.html)).

I wonder if you have plan to support those two options?

Thanks

**Comment by Ozsie** [comment]
Yes, I will add support for these options.

**Comment by Ozsie** [comment]
1.0.0-RC14-3 has been released with the requested options added
