### ISSUE TITLE
Not able to use plugin for Kotlin

### ISSUE THREAD

**Issue by ruchirnaphade** [Ozsie/detekt-maven-plugin#25]
I am trying to use this plugin for static code analysis for Kotlin but somehow, I am not able to use this correctly. I am getting below error when I put this in my POM file.

[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default) on project agathe: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Build failed with 55 weighted issues (threshold defined was 10). -> [Help 1]

Could you please assist me how can i resolve this issue?

Below is my POM file

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
        <kotlin.version>1.3.40</kotlin.version>
        <arrow.version>0.9.0</arrow.version>
        <binaryFolder>${basedir}/target/openshift-binarybuild</binaryFolder>
        <slf4jVersion>2.11.2</slf4jVersion>

        <sonar.language>kotlin</sonar.language>
        <sonar.sources>src/main/kotlin</sonar.sources>
        <sonar.tests>src/test/kotlin</sonar.tests>
        <sonar.coverage.jacoco.xmlReportPaths>${project.build.directory}/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.kotlin.detekt.reportPaths>${project.build.directory}/detekt.xml</sonar.kotlin.detekt.reportPaths>
        <sonar.host.url>https://sonarqube-otd-agathe.cnap-00-mp-prod.bmwgroup.net/</sonar.host.url>

        <detekt.version>1.0.0-RC16</detekt.version>
        <jcommander.version>1.72</jcommander.version>
        <detekt-maven-plugin.version>1.0.0-RC15</detekt-maven-plugin.version>
    </properties>

        <dependency>
            <groupId>io.gitlab.arturbosch.detekt</groupId>
            <artifactId>detekt-cli</artifactId>
            <version>${detekt.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>jcommander</artifactId>
                    <groupId>com.beust</groupId>
                </exclusion>
            </exclusions>
        </dependency>

            <plugin>
                <groupId>com.github.ozsie</groupId>
                <artifactId>detekt-maven-plugin</artifactId>
                <version>1.0.0-RC16</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <report>
                                <report>${project.basedir}/detekt.txt</report>
                                <report>${project.basedir}/detekt.xml</report>
                            </report>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by schalkms** [comment]
The plugin works correctly. Detekt fails the build if the threshold is met. Your code has 55 issues, but only 10 are allowed. 

> [ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default) on project agathe: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Build failed with 55 weighted issues (threshold defined was 10). -> [Help 1]

There are 3 ways to fix the build failure.

1. Update the [build failure threshold](https://arturbosch.github.io/detekt/failonbuild.html) to 56.
2. Fix the 55 issues in your code.
3. Deactivate the rules that flag your code. You can do this in the detekt [configuration file](https://arturbosch.github.io/detekt/configurations.html).

**Comment by Ozsie** [comment]
As @schalkms has answered, I'm closing this issue.
