### ISSUE TITLE
validate phase fails 

### ISSUE THREAD

**Issue by Geminist** [Ozsie/detekt-maven-plugin#29]
When check goal is attached to the validate phase mojo tries to make dependency resolution for test scope.
But some internal project artifacts are not accessible yet.

e.g.
```
<execution>
  <phase>validate</phase>
  <goals>
    <goal>check</goal>
  </goals>
</execution>
```

A
 - B
 - C depends on B

validation failed with:
"Could not resolve dependencies for C: Could not find artifact B:jar"

Is the use of a ResolutionScope.TEST as requiresDependencyResolution for check mojo justified?

**Comment by Ozsie** [comment]
It probably isn't, I'll have to do some more testing for this.

**Comment by Ozsie** [comment]
Release version 1.1.1 which contains the fix for this.
