### ISSUE TITLE
Plugin still can't be run from a parent multi-module project

### ISSUE THREAD

**Issue by Geminist** [Ozsie/detekt-maven-plugin#30]
The plugin is still skipped being run on the parent project with missing "src" folder.
But it is quite convenient to execute check for all sources as a single tree.

Related issue: #13

**Comment by Ozsie** [comment]
Can you describe how this is not working? I just did a trial run and the plugin executes for each child module as well as the parent project. Of course it won't scan the parent if no "src" folder is present, but I don't really see why that is an issue.

**Comment by Geminist** [comment]
I'm not sure that it's really useful case, but e.g. for multi-module project:
`
<plugin>
    <artifactId>detekt-maven-plugin</artifactId>
    <inherited>false</inherited>
    <executions>
        <execution>
            <phase>validate</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
...
`
plugin just ignores detect call.

**Comment by Ozsie** [comment]
That case feels rather useless, it does execute for the parent, however since there is no "src" folder nothing happens. The child modules are ignored since "inherited" is set to false.

**Comment by Geminist** [comment]
Of course. But just such case was a workaround for #29

**Comment by Geminist** [comment]
Alos, I understand that this looks unusual, but sourceDirectory can be customized in any module.

**Comment by Ozsie** [comment]
I made some changes that should make this work for you, and also make sure that the plugin is more flexible as to where sources are located as long as the input property is set to the new source location

**Comment by Geminist** [comment]
Thanks a lot!
And I hope that it will be useful not only for me

**Comment by Ozsie** [comment]
Release version 1.1.1 which contains the fix for this.
