### ISSUE TITLE
How to include extensions

### ISSUE THREAD

**Issue by jcchavezs** [Ozsie/detekt-maven-plugin#33]
Current documentation of detekt shows how to use extensions in Gradle. Worth to clarify it in here (e.g. for ktlint wrapper)?

https://arturbosch.github.io/detekt/extensions.html#integrate-your-extension-with-the-detekt-gradle-plugin

**Comment by Ozsie** [comment]
Absolutely, I'll have a look at updating the readme with examples.

**Comment by lucasfarre** [comment]
Hey guys! Any update regarding this issue? I'd like to use this plugin in order to run both ktlint and detekt, as it can be done with the gradle plugin.

**Comment by Ozsie** [comment]
Hi, sorry for the very long delay. I have updated the readme with instructions for adding detekt plugins to the plugin configuration
