### ISSUE TITLE
Add dependabot to repo

### ISSUE THREAD

**Issue by pinkasey** [Ozsie/detekt-maven-plugin#46]
See:
https://seankilleen.com/2019/07/automagically-update-your-package-dependencies-with-dependabot-for-free/

It's very handy, I recommend it.

**Comment by Ozsie** [comment]
Thanks, added it :)

**Comment by pinkasey** [comment]
Awesome!

Dependebot, it's all yours now

<img src="https://user-images.githubusercontent.com/1780369/82826514-f54db080-9eb5-11ea-828e-0372db1d3521.png"  width="200" height="200" />
