### ISSUE TITLE
Not able to configure threshold limit

### ISSUE THREAD

**Issue by icegoffy** [Ozsie/detekt-maven-plugin#64]
Hi I need help to configure a threshold limit, but somehow not able to find it, can you provide a quick sample?

**Comment by Ozsie** [comment]
Threshold limit is configured in detekts config file and is not part of this plugins configuration.

You can create a config file by running `mvn detekt:gc`. This will create `detekt.yml` in which you can find the configuration for threshold limit.

**Comment by icegoffy** [comment]
ok thanks for the prompt reply, here's how i put it in my maven pom:

`<plugin>
				<groupId>com.github.ozsie</groupId>
				<artifactId>detekt-maven-plugin</artifactId>
				<version>1.10.0</version>
				<executions>
					<execution>
						<phase>verify</phase>
						<goals>
							<goal>check</goal>
						</goals>
						<configuration>
							<report>
								<report>txt:reports/detekt.txt</report>
								<report>xml:reports/detekt.xml</report>
							</report>
							<config>kotlin-code-analysis-tool/detekt-config.yml</config>
						</configuration>
					</execution>
				</executions>
			</plugin>`

**Comment by Ozsie** [comment]
Then to set the threshold, edit `kotlin-code-analysis-tool/detekt-config.yml`. You can find info on it here https://arturbosch.github.io/detekt/configurations.html

Please note that this is outside the scope of this plugin. If you have further questions or issues with this, you should direct them to detekt at https://github.com/detekt/detekt
