### ISSUE TITLE
skip flag isn't working

### ISSUE THREAD

**Issue by currensy** [Ozsie/detekt-maven-plugin#78]
When `skip` flag is set to `true`  plugin still being executed. Looks like it's being overridden during execution:
https://github.com/Ozsie/detekt-maven-plugin/blob/6e19807efc7d389d35c92414c1f93f5f0a92111a/src/main/java/com/github/ozsie/CheckMojo.kt#L22
if `skip` flag is already set to `true` no need to evaluate the `input` dir

**Comment by Ozsie** [comment]
Thanks for the discovery and pull request. I have merged it and released version 1.14.2.1
