### ISSUE TITLE
Detekt 1.0.0.RC8 was released

### ISSUE THREAD

**Issue by duck8823** [Ozsie/detekt-maven-plugin#9]
Detekt version 1.0.0.RC8 was released. https://github.com/arturbosch/detekt/releases/tag/RC8
Are there any plans to release this plugin for version 1.0.0.RC8 ?

**Comment by Ozsie** [comment]
Yes, there is, but I can't give an estimate on when.

**Comment by Ozsie** [comment]
Sorry for the delay, but now version 1.0.0.RC8 has been released to Bintray

**Comment by duck8823** [comment]
Awesome ! Thanks !
